-- CreateTable
CREATE TABLE "logo" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "logo" TEXT NOT NULL,
    "createIn" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "upDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
